/*
================================================================================
  LedGerDB - Column Descriptions (MS_Description)
  Execute on existing database after 01/02 scripts.
  Safe to re-run: updates descriptions if they already exist.

  View in SSMS (important):
    1) Right-click table -> Design
    2) Click ONE column in the grid (e.g. Amount)
    3) Open bottom pane: "Column Properties"
    4) Find property "Description" (NOT the grid header comment)
    Or query:
      SELECT c.name, ep.value
      FROM sys.columns c
      LEFT JOIN sys.extended_properties ep
        ON ep.major_id=c.object_id AND ep.minor_id=c.column_id AND ep.name='MS_Description'
      WHERE c.object_id=OBJECT_ID('dbo.LedgerTransaction');

  Execute tip:
    - Recommended: open this file in SSMS and press F5
    - If using sqlcmd, file MUST be UTF-8 with BOM
================================================================================
*/

USE [LedGerDB];
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_SetDescription
    @TableName  SYSNAME,
    @ColumnName SYSNAME = NULL,
    @Description NVARCHAR(3750)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @level2type VARCHAR(128) = NULL;
    DECLARE @level2name SYSNAME = NULL;

    IF @ColumnName IS NOT NULL
    BEGIN
        SET @level2type = 'COLUMN';
        SET @level2name = @ColumnName;
    END

    IF EXISTS (
        SELECT 1
        FROM sys.extended_properties ep
        INNER JOIN sys.tables t ON ep.major_id = t.object_id
        WHERE t.object_id = OBJECT_ID(N'dbo.' + @TableName)
          AND ep.name = N'MS_Description'
          AND ep.class = 1
          AND (
                (@ColumnName IS NULL AND ep.minor_id = 0)
             OR (@ColumnName IS NOT NULL AND ep.minor_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.' + @TableName), @ColumnName, 'ColumnId'))
          )
    )
        EXEC sys.sp_updateextendedproperty
            @name = N'MS_Description', @value = @Description,
            @level0type = N'SCHEMA', @level0name = N'dbo',
            @level1type = N'TABLE',  @level1name = @TableName,
            @level2type = @level2type, @level2name = @level2name;
    ELSE
        EXEC sys.sp_addextendedproperty
            @name = N'MS_Description', @value = @Description,
            @level0type = N'SCHEMA', @level0name = N'dbo',
            @level1type = N'TABLE',  @level1name = @TableName,
            @level2type = @level2type, @level2name = @level2name;
END
GO

/* =============================================================================
   Sys_User
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @Description = N'System login users / 系统登录用户表';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'UserName', @Description = N'Login username, unique / 登录用户名，唯一';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'PasswordHash', @Description = N'Password hash generated by application / 密码哈希，由应用程序生成';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'PasswordSalt', @Description = N'Password salt / 密码盐值';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'DisplayName', @Description = N'Display name shown in UI / 界面显示名称';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'IsActive', @Description = N'Whether account is active: 1=Yes 0=No / 是否启用';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'LastLoginAt', @Description = N'Last login datetime / 最后登录时间';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'CreatedAt', @Description = N'Record created at UTC / 创建时间(UTC)';
EXEC dbo.usp_SetDescription @TableName = N'Sys_User', @ColumnName = N'UpdatedAt', @Description = N'Record updated at UTC / 更新时间(UTC)';
GO

/* =============================================================================
   Sys_TransactionType
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @Description = N'Transaction type dictionary / 流水类型字典表';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'Code', @Description = N'Stable code e.g. COLLECT_BDT_CASH / 类型编码';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'NameEn', @Description = N'English display name / 英文名称';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'NameZh', @Description = N'Chinese display name / 中文名称';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'Category', @Description = N'1=Inbound 2=Outbound 3=Transfer 4=System / 业务分类';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'AffectsCash', @Description = N'Whether this type affects cash on hand / 是否影响手头现金';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'AffectsBank', @Description = N'Whether this type affects bank account balance / 是否影响银行账户余额';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'AffectsPartyBalance', @Description = N'Whether this type affects party running balance / 是否影响参与方往来余额';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'RequireParty', @Description = N'UI rule: PartyId required / 录入时是否必填主参与方';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'RequireRelatedParty', @Description = N'UI rule: RelatedPartyId required / 录入时是否必填关联参与方';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'RequireBankAccount', @Description = N'UI rule: BankAccountId required / 录入时是否必填银行账户';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'RequirePaymentMode', @Description = N'UI rule: PaymentMode required / 录入时是否必填收款方式';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'RequirePayoutChannel', @Description = N'UI rule: PayoutChannel required / 录入时是否必填出货渠道';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'SortOrder', @Description = N'Sort order in dropdown lists / 下拉列表排序';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'IsActive', @Description = N'Whether type is active / 是否启用';
EXEC dbo.usp_SetDescription @TableName = N'Sys_TransactionType', @ColumnName = N'Remark', @Description = N'Optional notes / 备注';
GO

/* =============================================================================
   Party
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'Party', @Description = N'Business parties: customer, supplier, Shufen, other / 业务参与方表';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'Code', @Description = N'Short unique code e.g. FZL, SKT / 短编码，唯一';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'Name', @Description = N'Party full name / 参与方名称';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'PartyType', @Description = N'1=Customer 2=UsdtSupplier 3=Shufen 4=Other / 参与方类型';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'FinalAccountSide', @Description = N'Final Account side: 0=None 1=Credit(Receivable/Asset) 2=Debit(Payable/Liability) / 日终总账归属';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'ContactPhone', @Description = N'Contact phone optional / 联系电话';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'Remark', @Description = N'Optional notes / 备注';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'IsActive', @Description = N'Whether party is active / 是否启用';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'SortOrder', @Description = N'Sort order in lists / 列表排序';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'CreatedAt', @Description = N'Record created at UTC / 创建时间(UTC)';
EXEC dbo.usp_SetDescription @TableName = N'Party', @ColumnName = N'UpdatedAt', @Description = N'Record updated at UTC / 更新时间(UTC)';
GO

/* =============================================================================
   BankAccount
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @Description = N'Operator bank accounts for receiving/sending funds / 本人银行账户表';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'Code', @Description = N'Short unique code e.g. BB, City / 账户短编码，唯一';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'Name', @Description = N'Account display name / 账户显示名称';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'BankName', @Description = N'Bank institution name optional / 开户银行名称';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'AccountNo', @Description = N'Bank account number optional / 银行账号';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'Currency', @Description = N'Account currency: BDT/CNY/USDT, default BDT / 账户币种';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'FinalAccountSide', @Description = N'Final Account side, default 1=Credit(asset) / 日终总账归属，默认贷方资产';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'IsActive', @Description = N'Whether account is active / 是否启用';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'SortOrder', @Description = N'Sort order in lists / 列表排序';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'Remark', @Description = N'Optional notes / 备注';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'CreatedAt', @Description = N'Record created at UTC / 创建时间(UTC)';
EXEC dbo.usp_SetDescription @TableName = N'BankAccount', @ColumnName = N'UpdatedAt', @Description = N'Record updated at UTC / 更新时间(UTC)';
GO

/* =============================================================================
   OpeningBalance
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @Description = N'Opening balances entered on go-live day / 期初余额表';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'BalanceDate', @Description = N'Opening balance effective date, usually go-live date / 期初生效日期';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'EntityType', @Description = N'1=Party 2=BankAccount 3=Cash / 期初实体类型';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'PartyId', @Description = N'Referenced party when EntityType=1 / 参与方ID';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'BankAccountId', @Description = N'Referenced bank account when EntityType=2 / 银行账户ID';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'Currency', @Description = N'Currency code BDT/CNY/USDT / 币种';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'Amount', @Description = N'Signed opening amount. Positive=receivable/asset, negative=payable/liability / 有符号期初金额';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'Remark', @Description = N'Optional notes / 备注';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'CreatedByUserId', @Description = N'User who created this record / 录入人';
EXEC dbo.usp_SetDescription @TableName = N'OpeningBalance', @ColumnName = N'CreatedAt', @Description = N'Record created at UTC / 创建时间(UTC)';
GO

/* =============================================================================
   LedgerTransaction
   ============================================================================= */
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @Description = N'Core ledger transactions for all business flows / 核心流水表';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'Id', @Description = N'Primary key / 主键';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'TransNo', @Description = N'Business transaction number, optional unique / 业务流水号，可空唯一';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'TransDate', @Description = N'Business datetime, reports cut off at 00:00 by date / 业务发生时间';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'TransDateOnly', @Description = N'Persisted business date (computed), used for daily reports / 业务日期(计算列)';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'TransTypeId', @Description = N'FK to Sys_TransactionType / 流水类型ID';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PartyId', @Description = N'Primary party: customer, supplier or Shufen / 主参与方';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'RelatedPartyId', @Description = N'Related party e.g. supplier in triangular payment / 关联参与方';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'BankAccountId', @Description = N'Related bank account for bank in/out flows / 关联银行账户';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'Amount', @Description = N'Main transaction amount, must be > 0 / 主金额，必须大于0';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'Currency', @Description = N'Main amount currency: BDT/CNY/USDT / 主金额币种';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'UnitPrice', @Description = N'Exchange rate or unit price e.g. 126.10, 6.775, 18.65 / 汇率或单价';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'Quantity', @Description = N'Quantity amount e.g. USDT 137000 / 数量';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'QuantityCurrency', @Description = N'Quantity currency e.g. USDT / 数量币种';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'EquivalentAmount', @Description = N'Converted equivalent amount e.g. expected BDT from RMB sale / 换算金额';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'EquivalentCurrency', @Description = N'Equivalent amount currency / 换算金额币种';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PaymentMode', @Description = N'Customer BDT payment mode: 1=Cash 2=MyBank 3=SupplierBank / 客户付款方式';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PayMethod', @Description = N'Pay supplier method: 1=Cash 2=Bank / 付款给供应商方式';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PayoutChannel', @Description = N'RMB payout channel: 1=Alipay 2=WeChat 3=Bank / RMB出货渠道';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PayoutAccountName', @Description = N'Payout account holder name, optional / 出货账户户名';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'PayoutAccountNo', @Description = N'Payout account number, optional / 出货账号';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'IsOpening', @Description = N'Flag for opening-balance style transaction / 是否期初类流水';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'IsAdjustment', @Description = N'Flag for manual adjustment transaction / 是否调账流水';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'ReversedTransId', @Description = N'Original transaction id when this is a reversal/adjustment / 被冲正原流水ID';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'BatchNo', @Description = N'Batch number to group multiple lines entered together / 批次号';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'Remark', @Description = N'Free text remarks / 备注';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'CreatedByUserId', @Description = N'User who created this transaction / 录入人';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'CreatedAt', @Description = N'Record created at UTC / 创建时间(UTC)';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'UpdatedAt', @Description = N'Record updated at UTC / 更新时间(UTC)';
EXEC dbo.usp_SetDescription @TableName = N'LedgerTransaction', @ColumnName = N'IsDeleted', @Description = N'Soft delete flag: 1=deleted hidden from reports / 软删除标记';
GO

PRINT 'All table/column descriptions applied.';
GO

/* Optional: drop helper proc after apply
DROP PROCEDURE IF EXISTS dbo.usp_SetDescription;
GO
*/
